# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kSqcqC3DtFBYNnRx9XbQMxlPdke1Ooc
"""

import streamlit as st
import requests

API_URL = "https://genome-api.onrender.com"

st.title("Genome Clustering & Classification")

seq = st.text_area("Paste your RNA Sequence Below:")

if st.button("Classify"):
    res = requests.post(f"{API_URL}/classify", json={"sequence": seq})
    if res.status_code == 200:
        st.success(f"Lineage: {res.json()['lineage']}")
    else:
        st.error("Error from server")

if st.button("Cluster"):
    res = requests.post(f"{API_URL}/cluster", json={"sequence": seq})
    if res.status_code == 200:
        st.success(f"Cluster ID: {res.json()['cluster']}")
    else:
        st.error("Error from server")